// <auto-generated />
using EmailNotifications.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmailNotifications.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmailNotifications.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "client1@example.com",
                            Name = "Client 1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "client2@example.com",
                            Name = "Client 2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "client3@example.com",
                            Name = "Client 3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "client4@example.com",
                            Name = "Client 4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "client5@example.com",
                            Name = "Client 5"
                        });
                });

            modelBuilder.Entity("EmailNotifications.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHtmlContent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailContent = "<!DOCTYPE html>\r\n                                    <html>\r\n                                    <body>\r\n                                        <h2>Hello</h2>\r\n                                        <p>This is a notification from our system.</p>\r\n                                        <p>Promotional data from Template 1:</p>\r\n                                        <p>{{TemplateContent}}</p>\r\n                                        <p><a href=\"{{Url}}\">View Details</a></p>\r\n                                        <p><a href=\"{{UnsubscribeUrl}}\">Unsubscribe</a></p>\r\n                                    </body>\r\n                                    </html>",
                            EmailSubject = "Subject Template 1",
                            IsHtmlContent = true,
                            Name = "Template 1"
                        },
                        new
                        {
                            Id = 2,
                            EmailContent = "<!DOCTYPE html>\r\n                                    <html>\r\n                                    <body>\r\n                                        <h2>Hello</h2>\r\n                                        <p>This is a notification from our system.</p>\r\n                                        <p>We would like to promote something exciting:</p>\r\n                                        <p>{{TemplateContent}}</p>\r\n                                        <p><a href=\"{{Url}}\">View Details</a></p>\r\n                                        <p><a href=\"{{UnsubscribeUrl}}\">Unsubscribe</a></p>\r\n                                    </body>\r\n                                    </html>",
                            EmailSubject = "Subject Template 2",
                            IsHtmlContent = true,
                            Name = "Template 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
